### ISSUE TITLE
When will the code release?

### ISSUE THREAD

**Issue by SeaBird-Go** [ZrrSkywalker/I2P-MAE#1]
Hi, thanks for your wonderful work. I wonder when will the code release?

**Comment by whuhxb** [comment]
Hi @ZrrSkywalker 

Also looking forward to your excellent work. When the code will be released? Thanks a lot.

**Comment by ZrrSkywalker** [comment]
Sorry for the delay. We will release the code ASAP, within one week.

**Comment by whuhxb** [comment]
> Sorry for the delay. We will release the code ASAP, within one week.

Thanks so much!!

**Comment by auniquesun** [comment]
where is the code?

**Comment by ZrrSkywalker** [comment]
@auniquesun @whuhxb @SeaBird-1995 
Thanks for your waiting. The pre-training code of I2P-MAE has been released. The fine-tuning code will be open very soon.

**Comment by SeaBird-Go** [comment]
Thanks for sharing and opening this wonderful work~ 🎉
