### ISSUE TITLE
About code release

### ISSUE THREAD

**Issue by zyh16143998882** [ZrrSkywalker/I2P-MAE#2]
Thank you for your amazing work. May I ask when the code can be released? Will both pre-training and fine-tuning code be released? I noticed that your previous work, PointM2AE, only released the pre-training code and the fine-tuning code was repeatedly delayed.

**Comment by ZrrSkywalker** [comment]
@zyh16143998882 Sorry for making you wait. The complete pre-training and fine-tuning code of [Point-M2AE](https://github.com/ZrrSkywalker/Point-M2AE) has been released. I2P-MAE will be released very soon. Thanks.

**Comment by ZrrSkywalker** [comment]
The pre-training code of I2P-MAE has been released. Fine-tuning will be open in one day.

**Comment by zyh16143998882** [comment]
Thank you for your reply and efforts to release the code! However, all _.pth_ in I2P are currently not yet accessible and downloadable properly.
